# Generated by Django 4.0.4 on 2022-04-27 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_timestamp', models.DateTimeField()),
                ('user_id', models.CharField(max_length=20)),
                ('product_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
